---
title: "Der Autor: Hendrik Friederichs"
description: |
  Ich. Mensch. Arzt.
author:
  - name: Hendrik Friederichs 
    url: https://github.com/friedeh
    affiliation: Medizinische Fakultät Münster
    affiliation_url: https://medizin.uni-muenster.de
date: "`r Sys.Date()`"
output: radix::radix_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(VisualResume)
```

Lebenslauf Hendrik Friederichs

```{r}
VisualResume(
titles.left = c("Hendrik Friederichs, MD, MME", "Medicine, Medical Education, Medical Decision Making", "*Built with love in R using the VisualResume package: www.ndphillips.github.io/VisualResume"),
  titles.right = c("www.friederichs.science", "Hendrik.Friederichs@uni-muenster.de", "Full Resume: https://ndphillips.github.io/cv.html"),
  timeline.labels = c("Education", "Teaching"),
  timeline = data.frame(title = c("Marburg", "Münster", "Osnabrück", "Max Planck Institute", "Old Van", "Gray Matter", "Sandia Laboratories", "Assistenzarzt", "Studienhospital M??nster"),
                        sub = c("Vorklinkin", "Klinik", "Praktisches Jahr", "PhD. Researcher", "Methamphetamine Research", "Co-Founder", "Chemist", "Chemistry Teacher", "??rztlicher Leiter"),
                        start = c(1976, 1980.1, 1982.2, 1985, 1996.5, 1987, 1991, 1995, 2001),
                        end = c(1980, 1982, 1985, 1987, 1998, 1992, 1995, 1998, 2003),
                        side = c(1, 1, 1, 1, 1, 0, 0, 0, 0)),
  milestones = data.frame(title = c("MD", "PhD", "MME"),
                          sub = c("Medicine", "Medicine", "Medical Education"),
                          year = c(2002, 2012, 2004)),
  events = data.frame(year = c(1985, 1995, 1997, 1999, 2000),
                      title = c("Contributed to Nobel Prize winning experiment.",
                                "Honorary mention for best Chemistry teacher of the year.",
                                "Created Blue Sky, the most potent methamphetamine ever produced.",
                                "Made first $1,000,000.",
                                "White, W., & Pinkman, J. (2000). Blue Sky: A method of [...].\nJournal of Psychopharmical Substances, 1(1),.")),
  interests = list("statistics & programming" = c(rep("R", 10), rep("Decision Trees", 10), rep("Bayesian", 5)),
                   "statistics" = c(rep("Decision Trees", 10), rep("Bayesian", 5), rep("Regression", 3)),
                   "leadership" = c(rep("Motivation", 10), rep("Decision Making", 30), rep("Communication", 20))),
  year.steps = 2
)
```

```{r tables-publication}
# Liste der Publikationen über "rorcid" - noch optimierbar, aber gar nicht so schlecht > erst aktivieren, wenn Website online

# library(rorcid)
# (out <- works(orcid_id("0000-0001-9671-5235")))

# knitr::kable(out[1:17, 15], caption = 'A caption')
```




