---
title: "TEAMTHINK - gemeinsam besser entscheiden"
description: |
  Ein QVM-Projekt der Medizinischen Fakultät Münster
author:
  - name: Hendrik Friederichs
    url: https://www.friederichs.science
    affiliation: Institut für Ausbildung und Studienangelegenheiten (IfAS) der Medizinischen Fakultät Münster
    affiliation_url: https://medicampus.uni-muenster.de/ifas.html
date: "`r Sys.Date()`"
output: 
  radix::radix_article:
    toc: true
    toc_depth: 2
    self_contained: false
creative_commons: CC BY-NC
journal: null
doi: null
slug: friederichs2018Teamthink
citation_url: https://rstudio.github.io/friedeh
bibliography: "Papers_all.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tufte)
# Umwandlung in Powerpoint-Datei über rmarkdown::render("Medizin_article.Rmd", output_format = "powerpoint_presentation", output_options = list(reference_doc = "my-styles.pptx"))
# Umwandlung in Tufte-Handout über rmarkdown::render("Medizin_article.Rmd", output_format = "tufte_handout")
# Umwandlung in Word-Datei über rmarkdown::render("Medizin_article.Rmd", output_format = "word_document")
```

# Hintergrund

Ärzte müssen täglich viele – auch weitreichende – Entscheidungen fällen. Wer Entscheidungen fällt, muss diese auch verantworten, so dass Medizinern naturgemäß in der Behandlung von Patienten eine sehr große Verantwortung zufällt. Dementsprechend müssen Medizinstudierende lernen, wie man Entscheidungen fällt. Dabei reicht es nicht aus, dass man Entscheidungen nur aufgrund des aktuellen Wissensstandes erlernt - quasi wie einen Algorithmus. Da das medizinische Wissen sehr schnell wächst, ist es wichtig, generelle Entscheidungskompetenzen zu erwerben. Man muss z.B. lernen, wie man an wesentliche Informationen herankommt (Untersuchungstechniken, aber auch Recherche) und diese für den zu behandelnden Patienten gewichtet. Zudem wird die Zusammenarbeit mit den anderen Gesundheitsfachberufen immer wichtiger und so sind gemeinsame Entscheidungsfindungen im Team zu steuern und erfolgreich umzusetzen. Diese Entscheidungskompetenzen kann man dann im späteren Berufsleben jederzeit und unter verschiedensten Umständen anwenden. Im Augenblick lernen Studierende an der Medizinischen Fakultät Münster in den einzelnen klinischen Fächern, wie fachspezifische Entscheidungen zu fällen sind. Daraus eine generalisierte Entscheidungskompetenz zu entwickeln, wird den Studierenden selbst überlassen.

Den Studierenden sollten dementsprechend Einblicke, Werkzeuge und Modelle an die Hand gegeben werden, damit sie mit größerer Sicherheit, Vertrauen und einer deutlich höheren Effektivität entscheiden können.

# Konkrete Lernziele

Am Ende des Kurses werden die Teilnehmer in der Lage sein: 

* den Wert und die Grenzen Ihres derzeitigen Entscheidungsfindungsansatzes zu beschreiben 
* zu verstehen, wie sich äußere Einflüsse auf Ihre Entscheidungsfindung auswirken können 
* einen evidenzbasierten Rahmen für Entscheidungen zu verwenden 
* zu überlegen, wann und wie Sie andere in ihre Entscheidungsfindung einbeziehen 
* klare Handlungsoptionen für sich selbst zu identifizieren.


