---
title: "Workshop TEAMTHINK"
description: |
  gemeinsam entscheiden lernen
author:
  - name: Hendrik Friederichs
    url: https://www.friederichs.science
    affiliation: Institut für Ausbildung und Studienangelegenheiten (IfAS) der Medizinischen Fakultät Münster
    affiliation_url: https://medicampus.uni-muenster.de/ifas.html
date: "`r Sys.Date()`"
output: 
  radix::radix_article:
    toc: true
    toc_depth: 2
    self_contained: false
creative_commons: CC BY-NC
journal: null
doi: null
slug: friederichs2018WS_Teamthink
citation_url: https://rstudio.github.io/friedeh
bibliography: "Papers_all.bib"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tufte)
# Umwandlung in Powerpoint-Datei über rmarkdown::render("Medizin_article.Rmd", output_format = "powerpoint_presentation", output_options = list(reference_doc = "my-styles.pptx"))
# Umwandlung in Tufte-Handout über rmarkdown::render("Medizin_article.Rmd", output_format = "tufte_handout")
# Umwandlung in Word-Datei über rmarkdown::render("Medizin_article.Rmd", output_format = "word_document")
```

# Hintergrund

Wenn man Studierende mit den Grundsätzen klassischer Entscheidungsfindung und den erforderlichen statistischen Kompetenzen konfrontiert, kommt es eher zu negativen Assoziationen (bis hin zur Ablehnung). Dabei ist für Mediziner die mathematisch absolut korrekte Berechnung (z.B. „die Wahrscheinlichkeit für das Vorliegen der Erkrankung X liegt bei 68,3 %“) gar nicht so relevant. Vielmehr ist es wichtig, Diagnose- oder Therapiewahrscheinlichkeiten in ein angemessenes Verhältnis zu setzen (z.B. „der Husten des Patienten deutet mehr auf eine Lungenentzündung als auf ein Bronchial-Ca. hin“). Dementsprechend sind generalisierte Entscheidungskompetenzen für Mediziner viel relevanter und sollten intuitiv anwendbar sein.

Die Entwicklung einer generellen Entscheidungskompetenz ist für das ärztliche Arbeiten essenziell. Aufgrund der oben dargestellten Defizite möchten wir die Studierenden frühzeitig in ihrer generellen Entscheidungskompetenz schulen. Dabei soll insbesondere Wert auf das Entscheiden im Team gelegt werden.

So haben wir schon vorzeitig einen Pilot-Workshop im ersten Halbjahr durchgeführt. In der Durchführung dieses Workshops zeigte sich dann auch, dass die teilnehmenden Studierenden sehr von den „Hands-on-Einheiten“ mit einem hohen Grad an Interaktivität profitieren. Diese würden wir gerne weiterentwickeln und in das curriculare Angebot integrieren, um eine entsprechende Entscheidungskompetenz der Studierenden zu erreichen. 

Den Studierenden sollen Einblicke, Werkzeuge und Modelle an die Hand gegeben werden, damit sie mit größerer Sicherheit, Vertrauen und einer deutlich höheren Effektivität entscheiden können.

# Konkrete Lernziele

Am Ende des Kurses werden die Teilnehmer in der Lage sein: 
* den Wert und die Grenzen Ihres derzeitigen Entscheidungsfindungsansatzes zu beschreiben 
* zu verstehen, wie sich äußere Einflüsse auf Ihre Entscheidungsfindung auswirken können 
* einen evidenzbasierten Rahmen für Entscheidungen zu verwenden 
* zu überlegen, wann und wie Sie andere in ihre Entscheidungsfindung einbeziehen 
* klare Handlungsoptionen für sich selbst zu identifizieren.





